### ISSUE TITLE
Logique responsive

### ISSUE THREAD

**Issue by Antoine-D** [jeromebueno/3IW1-coiffeur#13]

**Comment by Antoine-D** [comment]
Pour rendre le projet plus accessible, nous avons mis en place une logique responsive design.
Nous avons donc étudié différents graphismes. Nous avons défini des ‘’break-points’’ qui correspondent aux intervalles de taille d’écran. 

Le CMS comportera donc quatre graphismes pour quatre types d’appareils :

	Pour les smartphones :
Le CMS sera fait en ‘’mobile-first’’ ce qui signifie que le tout premier graphisme du CMS sera réalisé pour une utilisation sur smartphone. Il comportera les points d’arrêt suivants :
o	Break-point minimum 576 px
o	Break-point maximum 768 px

	Nous aurons ensuite un graphisme pour la taille d’appareils au-dessus, les tablettes :
o	Break-point minimum 769 px
o	Break-point maximum 992 px

	Pour les écrans moyens (ordinateurs portables) :
o	Break-point minimum 993 px 
o	Break-point maximum 1200 px
	Pour les grands écrans (ordinateurs fixes) :
o	Break-point : si la taille dépasse 1200 px, ce graphisme sera appliqué.

**Comment by DylanSettbon** [comment]
https://docs.google.com/document/d/1dDoHNvZ2o0Di82J9qSdz06WPmEaDr1XMjiTwARVC420/edit?usp=sharing
