### ISSUE TITLE
Navigation et ergonomie

### ISSUE THREAD

**Issue by Antoine-D** [jeromebueno/3IW1-coiffeur#19]

**Comment by Sylvain6** [comment]
[Navigation et ergonomie.docx](https://github.com/jeromebueno/3IW1-coiffeur/files/1646097/Navigation.et.ergonomie.docx)

**Comment by Antoine-D** [comment]
Update !

[Navigation.et.ergonomie.docx](https://github.com/jeromebueno/3IW1-coiffeur/files/1646920/Navigation.et.ergonomie.docx)
