### ISSUE TITLE
Software et matériel

### ISSUE THREAD

**Issue by Antoine-D** [jeromebueno/3IW1-coiffeur#21]

**Comment by DylanSettbon** [comment]
https://docs.google.com/document/d/1nU4ien116g-bWHR10e5bsbXJtKm9_Y1GoO8hJDwjmjA/edit?usp=sharing

**Comment by DylanSettbon** [comment]
https://docs.google.com/document/d/1nU4ien116g-bWHR10e5bsbXJtKm9_Y1GoO8hJDwjmjA/edit

**Comment by DylanSettbon** [comment]
https://docs.google.com/document/d/1nU4ien116g-bWHR10e5bsbXJtKm9_Y1GoO8hJDwjmjA/edit#heading=h.q458sb7fjvez

**Comment by DylanSettbon** [comment]
https://docs.google.com/document/d/1nU4ien116g-bWHR10e5bsbXJtKm9_Y1GoO8hJDwjmjA/edit?usp=sharing

**Comment by DylanSettbon** [comment]
https://docs.google.com/document/d/1nU4ien116g-bWHR10e5bsbXJtKm9_Y1GoO8hJDwjmjA/edit?usp=sharing
