### ISSUE TITLE
Contexte

### ISSUE THREAD

**Issue by Antoine-D** [jeromebueno/3IW1-coiffeur#3]

**Comment by jeromebueno** [comment]
https://docs.google.com/document/d/11VoYTaD_qsl2cnFtUOK6EM8nbR6hEWMgRkKaK5x5Q6c/edit?usp=sharing

**Comment by Sylvain6** [comment]
[Contexte.docx](https://github.com/jeromebueno/3IW1-coiffeur/files/1660692/Contexte.docx)

**Comment by Sylvain6** [comment]
[Contexte.docx](https://github.com/jeromebueno/3IW1-coiffeur/files/1664023/Contexte.docx)

**Comment by jeromebueno** [comment]
[Contexte.docx](https://github.com/jeromebueno/3IW1-coiffeur/files/1664648/Contexte.docx)
