### ISSUE TITLE
Mapping - Zonning

### ISSUE THREAD

**Issue by Antoine-D** [jeromebueno/3IW1-coiffeur#31]

**Comment by Sylvain6** [comment]
![image](https://user-images.githubusercontent.com/24957868/35530243-d23c2ca2-0533-11e8-92fc-bad71e1f2e7b.png)

**Comment by Sylvain6** [comment]
Mapping et zoning.
Afin de répondre à un besoin de practicité, la barre de navigation sera commune à toutes les pages. Cette dernière sera composée d'un accès direct aux onglets principaux (qui seront ainsi mis en avant, et donc facile d'accès pour l'utilisateur), mais aussi d'un logo. 
Pour que le site donne envie nous avons disposé un container à images (qui défilent) pour donner envie à l'utilisateur, qu'il sache de suite de quoi il s'agit mais aussi d'apporter une touche de dynamisme avec du mouvement direct sur la page. 
Nous avons aussi pris la décision de tout disposer sur la page d'accueil afin de limiter l'action du scroll à l'utilisateur et lui faciliter l'accès au contenu. Par la suite nous avons donc placer quelques articles qui porteront sur une veille (surement sur le thème de la coiffure) ou bien sur l'actualité du salon (prix, nouveaux employés, nouveaux tarifs etc). Pour continuer dans cet esprit nous avons, sur le côté, un flux RSS d'un réseau social du salon.
