### ISSUE TITLE
Objectifs

### ISSUE THREAD

**Issue by Antoine-D** [jeromebueno/3IW1-coiffeur#4]

**Comment by Antoine-D** [comment]
Le projet MyHair’App est un projet de Content Manager System (CMS), qui consiste à proposer aux salons de coiffure un site web dont l’architecture a été préconçue mais qui sera personnalisables par les clients.

En effet, l’application est un logiciel en ligne qui proposera deux architectures possibles :

	Un site vitrine qui affichera les prestations proposées par le salon. Le client pourra ensuite choisir sa ou ses prestation(s) et les réserver. Aucun paiement ne sera demandé pour les prestations.il aura également une partie de gestion d’un contenu promotionnel (par système d’actualités et flux RSS). 


	Un site e-commerce qui reprends l’ensemble des fonctionnalités du site précédent en y ajoutant une partie boutique qui proposera des produits de la marque affiliée au salon à la vente.

L’objectif principal est donc de pouvoir toucher le plus grand public possible, allant du salon de coiffure indépendant (qui ne nécessite peut-être pas d’avoir un site e-commerce) jusqu’à la chaine de salons de coiffures qui pourraient vouloir ce type de site pour promouvoir leur marque.

**Comment by DylanSettbon** [comment]
https://docs.google.com/document/d/1t_MUHH56fz4H58E6GND4wbD_SnSQ6FNLU92JQk4k474/edit?usp=sharing
