### ISSUE TITLE
Deadline

### ISSUE THREAD

**Issue by Antoine-D** [jeromebueno/3IW1-coiffeur#5]

**Comment by Antoine-D** [comment]
deadline n°1 : 30/01/2018
deadline n°2 : 20/02/2018 // a verifier => partiel intégration
deadline n°3 : 27/03/2018
deadline n°4 : 09/04/2018

ensuite il faudra voir ensemble

**Comment by Sylvain6** [comment]
go mettre la deadline de février pour les maquettes + codes du front
