### ISSUE TITLE
Contenu du site

### ISSUE THREAD

**Issue by Antoine-D** [jeromebueno/3IW1-coiffeur#6]

**Comment by Antoine-D** [comment]
![contenu du site](https://user-images.githubusercontent.com/32832698/34732475-b55b2990-f565-11e7-88c4-f5945f260d6d.png)

**Comment by Sylvain6** [comment]
[Contenu du site.docx](https://github.com/jeromebueno/3IW1-coiffeur/files/1620124/Contenu.du.site.docx)

**Comment by Sylvain6** [comment]
[Contenu du site.docx](https://github.com/jeromebueno/3IW1-coiffeur/files/1626759/Contenu.du.site.docx)

**Comment by Antoine-D** [comment]
![capture d ecran 2018-01-19 a 16 15 18](https://user-images.githubusercontent.com/32832698/35157334-f5d44fc6-fd33-11e7-8341-f625f7a0f4c7.png)
