### ISSUE TITLE
Présentation

### ISSUE THREAD

**Issue by Antoine-D** [jeromebueno/3IW1-coiffeur#8]

**Comment by jeromebueno** [comment]
Présentation du groupe

Le groupe 3 de la filière Ingénierie Web session 2017/2018  (classe 1) est composé de quatres membres :
- Dylan Settbon
- Jerome Bueno
- Sylvain Coutrot
- Antoine Dumont

Présentation du projet

Hair’App est un CMS ayant pour but de simplifier la création de site web pour les salon de coiffure non franchisé. il permet la création d’un site web professionnel orienté vers l’univers de la coiffure et proposant des fonctionnalités en rapport avec celui-ci comme la prise de rendez-vous en ligne ou l’affichage de la carte du salon

Qu’est-ce qu’un CMS ?
Un système de gestion de contenu  est un logiciel utilisés pour créer et gérer du contenu numérique. Les CMS sont généralement utilisés pour la gestion de contenu Web.

Cible

Nos cibles sont les salons de coiffures non franchisés, c’est-à-dire les salons de coiffure n’appartenant pas à un grand groupe et n’ayant pas une grande visibilité sur le web

**Comment by jeromebueno** [comment]
il faut regrouper la presentation et le contexte
